( function( b8 ) {

	b8.Collision = {};

	b8.COLLISION = {};
	b8.COLLISION.NONE = 0;
	b8.COLLISION.N = 1;
	b8.COLLISION.E = 2;
	b8.COLLISION.S = 4;
	b8.COLLISION.W = 8;
	b8.COLLISION.NE = b8.COLLISION.N + b8.COLLISION.E;
	b8.COLLISION.NS = b8.COLLISION.N + b8.COLLISION.S;
	b8.COLLISION.NW = b8.COLLISION.N + b8.COLLISION.W;
	b8.COLLISION.SE = b8.COLLISION.S + b8.COLLISION.E;
	b8.COLLISION.SW = b8.COLLISION.S + b8.COLLISION.W;
	b8.COLLISION.WE = b8.COLLISION.W + b8.COLLISION.E;
	b8.COLLISION.WNE = b8.COLLISION.W + b8.COLLISION.N + b8.COLLISION.E;
	b8.COLLISION.WES = b8.COLLISION.W + b8.COLLISION.E + b8.COLLISION.S;
	b8.COLLISION.NES = b8.COLLISION.N + b8.COLLISION.E + b8.COLLISION.S;
	b8.COLLISION.ALL = b8.COLLISION.N + b8.COLLISION.E + b8.COLLISION.S + b8.COLLISION.W;

} )( b8 );
